### ISSUE TITLE
RunTimeTicks error

### ISSUE THREAD

**Issue by peterbaumert** [thewhobox/ioBroker.emby#13]
emby.0 | 2020-10-04 22:06:03.519 | info | (9018) terminating
-- | -- | -- | --
emby.0 | 2020-10-04 22:06:03.499 | error | at processTicksAndRejections (internal/process/task_queues.js:79:11)
emby.0 | 2020-10-04 22:06:03.499 | error | at /opt/iobroker/node_modules/websocket/lib/WebSocketConnection.js:323:40
emby.0 | 2020-10-04 22:06:03.499 | error | at WebSocketConnection.processFrame (/opt/iobroker/node_modules/websocket/lib/WebSocketConnection.js:554:26)
emby.0 | 2020-10-04 22:06:03.499 | error | at WebSocketConnection.emit (events.js:315:20)
emby.0 | 2020-10-04 22:06:03.499 | error | at WebSocketConnection.<anonymous> (/opt/iobroker/node_modules/websocket/lib/W3CWebSocket.js:205:19)
emby.0 | 2020-10-04 22:06:03.499 | error | at W3CWebSocket.onMessage (/opt/iobroker/node_modules/websocket/lib/W3CWebSocket.js:234:14)
emby.0 | 2020-10-04 22:06:03.499 | error | at W3CWebSocket._dispatchEvent [as dispatchEvent] (/opt/iobroker/node_modules/yaeti/lib/EventTarget.js:107:17)
emby.0 | 2020-10-04 22:06:03.499 | error | at W3CWebSocket.webMessage [as onmessage] (/opt/iobroker/node_modules/iobroker.emby/main.js:360:72)
emby.0 | 2020-10-04 22:06:03.499 | error | (9018) TypeError: Cannot read property 'RunTimeTicks' of null
emby.0 | 2020-10-04 22:06:03.498 | error | (9018) uncaught exception: Cannot read property 'RunTimeTicks' of null

**Comment by thewhobox** [comment]
Hallo, kann den Fehler leider nicht reproduzieren.
Hab mal einen kleinen Fix um den Fehler gebaut, kann ich aber selbst nicht testen und daher nur in der Githab variante verfügbar.
