### ISSUE TITLE
Weitere Infos abfragen

### ISSUE THREAD

**Issue by Oliver6911** [thewhobox/ioBroker.emby#14]
Hallo thewhobox,
wollte dir eigentlich im ioBroker Forum schreiben, aber leider ist der Thread geschlossen. 
Ist es möglich weitere Informationen vom emby-Server abzurufen?

Schön wäre es, wenn noch folgendes abgefragt würde:

1. Tagline des Filmes
2. Bewertung
3. Bild vom Fanart
4. Originaltitel

Gruß Oliver

**Comment by Oliver6911** [comment]
Sorry, wurde leider doppelt angelegt.

**Comment by thewhobox** [comment]
Duplikat https://github.com/thewhobox/ioBroker.emby/issues/15
