### ISSUE TITLE
Zusätzliche Informationen auslesen

### ISSUE THREAD

**Issue by Oliver6911** [thewhobox/ioBroker.emby#15]
Hallo thewhobox,
wollte dir eigentlich im ioBroker Forum schreiben, aber leider ist der Thread geschlossen. 
Ist es möglich weitere Informationen vom emby-Server abzurufen?

Schön wäre es, wenn noch folgendes abgefragt würde:

1. Tagline des Filmes
2. Bewertung
3. Bild vom Fanart
4. Originaltitel

Gruß Oliver

**Comment by thewhobox** [comment]
Hallo Oliver,

ich hab leider seit längerem kein iobroker mehr im Einsatz.
Könnte es die Tage mal bei meinem emby ausprobieren was der schickt und dann ohne Vorbehalt einfügen. Dann kannst es testen.

**Comment by thewhobox** [comment]
Also folgende Infos könnte man hinzufügen:

Name
Original Titel
External Urls (Imdb/TheMovieDb)
Pfad
Altersfreigabe
Beschreibung
Tagline
Genres
Bewertungen
Produktionsjahr
Type (Film/Musik/Bild)
Bildverhätlnis (16:9/20:9/4:3)
BildTag
BackdropImageTag
Höhe
Breite

AppIcon
Benutzername
Client
Playlist länge
Playlist Index
Abspielmethode (Direkt/Konvertiert)

**Comment by Oliver6911** [comment]
Hallo Mike,

 

erstmal danke für deine Antwort und sorry für meine verspätete Reaktion.

 

Folgende Inhalte wären für mich interessant:

 

Name
Original Titel
Altersfreigabe
Beschreibung
Tagline
Genres
Bewertungen
Produktionsjahr
Type (Film/Musik/Bild)
Bildverhätlnis (16:9/20:9/4:3)
BildTag
BackdropImageTag

 

Gruß

Oliver



 

Von: Mike <notifications@github.com> 
Gesendet: Donnerstag, 11. Februar 2021 09:38
An: thewhobox/ioBroker.emby <ioBroker.emby@noreply.github.com>
Cc: Oliver6911 <oliver.boehm69@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [thewhobox/ioBroker.emby] Zusätzliche Informationen auslesen (#15)

 

Also folgende Infos könnte man hinzufügen:

Name
Original Titel
External Urls (Imdb/TheMovieDb)
Pfad
Altersfreigabe
Beschreibung
Tagline
Genres
Bewertungen
Produktionsjahr
Type (Film/Musik/Bild)
Bildverhätlnis (16:9/20:9/4:3)
BildTag
BackdropImageTag
Höhe
Breite

AppIcon
Benutzername
Client
Playlist länge
Playlist Index
Abspielmethode (Direkt/Konvertiert)

**Comment by thewhobox** [comment]
okay, ich hab mal ein paar Infos hinzugefügt.
Die Version 1.0.3 ist nun auf Github. 
Wäre super, wenn du das kurz testen könntest und hier Rückmeldung geben.

**Comment by Oliver6911** [comment]
Hallo Mike,

 

ist alles da, bis auf das Bildverhältnis.

Beim BackdropImageTag dachte ich eigentlich, dass da der Pfad erscheint, damit ich es mir anzeigen lassen kann.

 

Wenn das nicht funktioniert ist es auch kein Thema.

 

Danke fürs einbauen.

 

Gruß Oliver

 

Von: Mike <notifications@github.com> 
Gesendet: Donnerstag, 4. März 2021 12:04
An: thewhobox/ioBroker.emby <ioBroker.emby@noreply.github.com>
Cc: Oliver6911 <oliver.boehm69@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [thewhobox/ioBroker.emby] Zusätzliche Informationen auslesen (#15)

 

okay, ich hab mal ein paar Infos hinzugefügt.
Die Version 1.0.3 ist nun auf Github.
Wäre super, wenn du das kurz testen könntest und hier Rückmeldung geben.

**Comment by Oliver6911** [comment]
Hallo Mike,

 

etwas ist mir jetzt doch noch aufgefallen, der Datenpunkt Rating wird nur überschrieben, wenn ein neues Rating vorhanden ist, ansonsten bleibt die alte Bewertung stehen.

 

Gruß Oliver

 

Von: Mike <notifications@github.com> 
Gesendet: Donnerstag, 4. März 2021 12:04
An: thewhobox/ioBroker.emby <ioBroker.emby@noreply.github.com>
Cc: Oliver6911 <oliver.boehm69@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [thewhobox/ioBroker.emby] Zusätzliche Informationen auslesen (#15)

 

okay, ich hab mal ein paar Infos hinzugefügt.
Die Version 1.0.3 ist nun auf Github.
Wäre super, wenn du das kurz testen könntest und hier Rückmeldung geben.

**Comment by thewhobox** [comment]
Hallo Oliver,

die Bilder sind im Unterordner Poster. Dort gibt es dann Main (für Filme und bei Serien das Hauptbild) und wenn es ne Serie ist gibt es auch Staffel und Episoden Poster. 
Die Bilder sind dann als URL angegeben.
Bildverhältnis bekomme ich auch iwie nicht bei jedem Video.

Hab die Github Version etwas angepasst.
