### ISSUE TITLE
Repo type !== io-package type

### ISSUE THREAD

**Issue by ldittmar81** [thewhobox/ioBroker.emby#3]
https://github.com/thewhobox/ioBroker.emby/blob/master/io-package.json#L103

![11-03-_2019_09-23-10](https://user-images.githubusercontent.com/9552828/54109612-67d08e80-43df-11e9-9ed5-9558375f2dab.png)

Please choose the same type in io-package and repo.

https://github.com/thewhobox/ioBroker.emby/blob/master/io-package.json#L91

The Author is also missing.

Thx

**Comment by thewhobox** [comment]
Hey,
i already changed the author and changed the type now.

Thanks for the reminder.
