### ISSUE TITLE
Added delay if you watch mor episodes

### ISSUE THREAD

**Issue by MattL0** [thewhobox/ioBroker.emby#8]
hi, thanks for this really nice adapter. 

Could you explain me the exact impact of this ? i am not sure to understand ? and is is in seconds?
I have set mine to 50. What does this mean?

thanks !!
Matt

**Comment by thewhobox** [comment]
Hello,

it is set in milliseconds.
If a episode ands and you autoplay the next episode, emby will set the state to pause for a few milliseconds.
If you contole lights depending on the play state its very annoying if the lights go off and on when the next episode starts.
The delay skips this playstate so lights dont turn off and on.

I tested it with 500 milliseconds and its working good.

**Comment by MattL0** [comment]
Than you
